// Generated by /mnt/d/Programs/Code/c++/xenodochial_banzai-tiger-2024/build-aux/bin/authors.h-gen, do not edit by hand.

#define PACKAGE_SHORT_AUTHORS \


#define PACKAGE_AUTHORS \
  "Celestine Bouchelet <celestine.bouchelet@epita.fr>\n"                     \
  "Agathe Maeght <agathe.maeght@epita.fr>\n"                                 \
  "Quentin Escudier <quentin.escudier@epita.fr>\n"                           \
  "Tom Genlis <tom.genlis@epita.fr>\n"
